version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: /opt/venv/bin/python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/srv/app
    environment:
      - PYTHONPATH=/srv/app
      - DJANGO_SETTINGS_MODULE=DjangoProject1.settings
    working_dir: /srv/app
